import { Buffer } from 'node:buffer';
import { Gibbon } from '@icazemier/gibbons';

/**
 * Represents a user row stored in PostgreSQL.
 * Each user has a UUID id and bitwise masks for group memberships and aggregated permissions.
 *
 * Arbitrary metadata fields supplied by the caller are flattened onto this object
 * (e.g. `name`, `email`) and persisted in a JSONB column.
 */
export interface IGibbonUser {
  /** UUID primary key generated by PostgreSQL (`gen_random_uuid()`) */
  id: string;
  /** Bitwise mask of aggregated permissions derived from group memberships */
  permissionsGibbon: Buffer | Gibbon;
  /** Bitwise mask of groups this user is subscribed to */
  groupsGibbon: Buffer | Gibbon;
  /** Arbitrary metadata fields persisted as JSONB */
  [key: string]: unknown;
}
